// source: complex.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.example.complex.ComplexMessage');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.example.complex.DummyMessage');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.example.complex.ComplexMessage = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.example.complex.ComplexMessage.repeatedFields_, null);
};
goog.inherits(proto.example.complex.ComplexMessage, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.example.complex.ComplexMessage.displayName = 'proto.example.complex.ComplexMessage';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.example.complex.ComplexMessage.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.example.complex.ComplexMessage.prototype.toObject = function(opt_includeInstance) {
  return proto.example.complex.ComplexMessage.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.example.complex.ComplexMessage} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.example.complex.ComplexMessage.toObject = function(includeInstance, msg) {
  var f, obj = {
    oneDummy: (f = msg.getOneDummy()) && proto.example.complex.DummyMessage.toObject(includeInstance, f),
    multipleDummyList: jspb.Message.toObjectList(msg.getMultipleDummyList(),
    proto.example.complex.DummyMessage.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.example.complex.ComplexMessage}
 */
proto.example.complex.ComplexMessage.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.example.complex.ComplexMessage;
  return proto.example.complex.ComplexMessage.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.example.complex.ComplexMessage} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.example.complex.ComplexMessage}
 */
proto.example.complex.ComplexMessage.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 2:
      var value = new proto.example.complex.DummyMessage;
      reader.readMessage(value,proto.example.complex.DummyMessage.deserializeBinaryFromReader);
      msg.setOneDummy(value);
      break;
    case 3:
      var value = new proto.example.complex.DummyMessage;
      reader.readMessage(value,proto.example.complex.DummyMessage.deserializeBinaryFromReader);
      msg.addMultipleDummy(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.example.complex.ComplexMessage.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.example.complex.ComplexMessage.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.example.complex.ComplexMessage} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.example.complex.ComplexMessage.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOneDummy();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.example.complex.DummyMessage.serializeBinaryToWriter
    );
  }
  f = message.getMultipleDummyList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.example.complex.DummyMessage.serializeBinaryToWriter
    );
  }
};


/**
 * optional DummyMessage one_dummy = 2;
 * @return {?proto.example.complex.DummyMessage}
 */
proto.example.complex.ComplexMessage.prototype.getOneDummy = function() {
  return /** @type{?proto.example.complex.DummyMessage} */ (
    jspb.Message.getWrapperField(this, proto.example.complex.DummyMessage, 2));
};


/**
 * @param {?proto.example.complex.DummyMessage|undefined} value
 * @return {!proto.example.complex.ComplexMessage} returns this
*/
proto.example.complex.ComplexMessage.prototype.setOneDummy = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.example.complex.ComplexMessage} returns this
 */
proto.example.complex.ComplexMessage.prototype.clearOneDummy = function() {
  return this.setOneDummy(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.example.complex.ComplexMessage.prototype.hasOneDummy = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * repeated DummyMessage multiple_dummy = 3;
 * @return {!Array<!proto.example.complex.DummyMessage>}
 */
proto.example.complex.ComplexMessage.prototype.getMultipleDummyList = function() {
  return /** @type{!Array<!proto.example.complex.DummyMessage>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.example.complex.DummyMessage, 3));
};


/**
 * @param {!Array<!proto.example.complex.DummyMessage>} value
 * @return {!proto.example.complex.ComplexMessage} returns this
*/
proto.example.complex.ComplexMessage.prototype.setMultipleDummyList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.example.complex.DummyMessage=} opt_value
 * @param {number=} opt_index
 * @return {!proto.example.complex.DummyMessage}
 */
proto.example.complex.ComplexMessage.prototype.addMultipleDummy = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.example.complex.DummyMessage, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.example.complex.ComplexMessage} returns this
 */
proto.example.complex.ComplexMessage.prototype.clearMultipleDummyList = function() {
  return this.setMultipleDummyList([]);
};


