// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: complex.proto

package example.complex;

public final class Complex {
  private Complex() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ComplexMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:example.complex.ComplexMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.example.complex.DummyMessage one_dummy = 2;</code>
     * @return Whether the oneDummy field is set.
     */
    boolean hasOneDummy();
    /**
     * <code>.example.complex.DummyMessage one_dummy = 2;</code>
     * @return The oneDummy.
     */
    example.complex.Complex.DummyMessage getOneDummy();
    /**
     * <code>.example.complex.DummyMessage one_dummy = 2;</code>
     */
    example.complex.Complex.DummyMessageOrBuilder getOneDummyOrBuilder();

    /**
     * <code>repeated .example.complex.DummyMessage multiple_dummy = 3;</code>
     */
    java.util.List<example.complex.Complex.DummyMessage> 
        getMultipleDummyList();
    /**
     * <code>repeated .example.complex.DummyMessage multiple_dummy = 3;</code>
     */
    example.complex.Complex.DummyMessage getMultipleDummy(int index);
    /**
     * <code>repeated .example.complex.DummyMessage multiple_dummy = 3;</code>
     */
    int getMultipleDummyCount();
    /**
     * <code>repeated .example.complex.DummyMessage multiple_dummy = 3;</code>
     */
    java.util.List<? extends example.complex.Complex.DummyMessageOrBuilder> 
        getMultipleDummyOrBuilderList();
    /**
     * <code>repeated .example.complex.DummyMessage multiple_dummy = 3;</code>
     */
    example.complex.Complex.DummyMessageOrBuilder getMultipleDummyOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code example.complex.ComplexMessage}
   */
  public  static final class ComplexMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:example.complex.ComplexMessage)
      ComplexMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ComplexMessage.newBuilder() to construct.
    private ComplexMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ComplexMessage() {
      multipleDummy_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ComplexMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ComplexMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 18: {
              example.complex.Complex.DummyMessage.Builder subBuilder = null;
              if (oneDummy_ != null) {
                subBuilder = oneDummy_.toBuilder();
              }
              oneDummy_ = input.readMessage(example.complex.Complex.DummyMessage.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(oneDummy_);
                oneDummy_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                multipleDummy_ = new java.util.ArrayList<example.complex.Complex.DummyMessage>();
                mutable_bitField0_ |= 0x00000001;
              }
              multipleDummy_.add(
                  input.readMessage(example.complex.Complex.DummyMessage.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          multipleDummy_ = java.util.Collections.unmodifiableList(multipleDummy_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return example.complex.Complex.internal_static_example_complex_ComplexMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return example.complex.Complex.internal_static_example_complex_ComplexMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              example.complex.Complex.ComplexMessage.class, example.complex.Complex.ComplexMessage.Builder.class);
    }

    public static final int ONE_DUMMY_FIELD_NUMBER = 2;
    private example.complex.Complex.DummyMessage oneDummy_;
    /**
     * <code>.example.complex.DummyMessage one_dummy = 2;</code>
     * @return Whether the oneDummy field is set.
     */
    public boolean hasOneDummy() {
      return oneDummy_ != null;
    }
    /**
     * <code>.example.complex.DummyMessage one_dummy = 2;</code>
     * @return The oneDummy.
     */
    public example.complex.Complex.DummyMessage getOneDummy() {
      return oneDummy_ == null ? example.complex.Complex.DummyMessage.getDefaultInstance() : oneDummy_;
    }
    /**
     * <code>.example.complex.DummyMessage one_dummy = 2;</code>
     */
    public example.complex.Complex.DummyMessageOrBuilder getOneDummyOrBuilder() {
      return getOneDummy();
    }

    public static final int MULTIPLE_DUMMY_FIELD_NUMBER = 3;
    private java.util.List<example.complex.Complex.DummyMessage> multipleDummy_;
    /**
     * <code>repeated .example.complex.DummyMessage multiple_dummy = 3;</code>
     */
    public java.util.List<example.complex.Complex.DummyMessage> getMultipleDummyList() {
      return multipleDummy_;
    }
    /**
     * <code>repeated .example.complex.DummyMessage multiple_dummy = 3;</code>
     */
    public java.util.List<? extends example.complex.Complex.DummyMessageOrBuilder> 
        getMultipleDummyOrBuilderList() {
      return multipleDummy_;
    }
    /**
     * <code>repeated .example.complex.DummyMessage multiple_dummy = 3;</code>
     */
    public int getMultipleDummyCount() {
      return multipleDummy_.size();
    }
    /**
     * <code>repeated .example.complex.DummyMessage multiple_dummy = 3;</code>
     */
    public example.complex.Complex.DummyMessage getMultipleDummy(int index) {
      return multipleDummy_.get(index);
    }
    /**
     * <code>repeated .example.complex.DummyMessage multiple_dummy = 3;</code>
     */
    public example.complex.Complex.DummyMessageOrBuilder getMultipleDummyOrBuilder(
        int index) {
      return multipleDummy_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (oneDummy_ != null) {
        output.writeMessage(2, getOneDummy());
      }
      for (int i = 0; i < multipleDummy_.size(); i++) {
        output.writeMessage(3, multipleDummy_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (oneDummy_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getOneDummy());
      }
      for (int i = 0; i < multipleDummy_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, multipleDummy_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof example.complex.Complex.ComplexMessage)) {
        return super.equals(obj);
      }
      example.complex.Complex.ComplexMessage other = (example.complex.Complex.ComplexMessage) obj;

      if (hasOneDummy() != other.hasOneDummy()) return false;
      if (hasOneDummy()) {
        if (!getOneDummy()
            .equals(other.getOneDummy())) return false;
      }
      if (!getMultipleDummyList()
          .equals(other.getMultipleDummyList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasOneDummy()) {
        hash = (37 * hash) + ONE_DUMMY_FIELD_NUMBER;
        hash = (53 * hash) + getOneDummy().hashCode();
      }
      if (getMultipleDummyCount() > 0) {
        hash = (37 * hash) + MULTIPLE_DUMMY_FIELD_NUMBER;
        hash = (53 * hash) + getMultipleDummyList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static example.complex.Complex.ComplexMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static example.complex.Complex.ComplexMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static example.complex.Complex.ComplexMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static example.complex.Complex.ComplexMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static example.complex.Complex.ComplexMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static example.complex.Complex.ComplexMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static example.complex.Complex.ComplexMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static example.complex.Complex.ComplexMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static example.complex.Complex.ComplexMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static example.complex.Complex.ComplexMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static example.complex.Complex.ComplexMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static example.complex.Complex.ComplexMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(example.complex.Complex.ComplexMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code example.complex.ComplexMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:example.complex.ComplexMessage)
        example.complex.Complex.ComplexMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return example.complex.Complex.internal_static_example_complex_ComplexMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return example.complex.Complex.internal_static_example_complex_ComplexMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                example.complex.Complex.ComplexMessage.class, example.complex.Complex.ComplexMessage.Builder.class);
      }

      // Construct using example.complex.Complex.ComplexMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getMultipleDummyFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (oneDummyBuilder_ == null) {
          oneDummy_ = null;
        } else {
          oneDummy_ = null;
          oneDummyBuilder_ = null;
        }
        if (multipleDummyBuilder_ == null) {
          multipleDummy_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          multipleDummyBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return example.complex.Complex.internal_static_example_complex_ComplexMessage_descriptor;
      }

      @java.lang.Override
      public example.complex.Complex.ComplexMessage getDefaultInstanceForType() {
        return example.complex.Complex.ComplexMessage.getDefaultInstance();
      }

      @java.lang.Override
      public example.complex.Complex.ComplexMessage build() {
        example.complex.Complex.ComplexMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public example.complex.Complex.ComplexMessage buildPartial() {
        example.complex.Complex.ComplexMessage result = new example.complex.Complex.ComplexMessage(this);
        int from_bitField0_ = bitField0_;
        if (oneDummyBuilder_ == null) {
          result.oneDummy_ = oneDummy_;
        } else {
          result.oneDummy_ = oneDummyBuilder_.build();
        }
        if (multipleDummyBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            multipleDummy_ = java.util.Collections.unmodifiableList(multipleDummy_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.multipleDummy_ = multipleDummy_;
        } else {
          result.multipleDummy_ = multipleDummyBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof example.complex.Complex.ComplexMessage) {
          return mergeFrom((example.complex.Complex.ComplexMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(example.complex.Complex.ComplexMessage other) {
        if (other == example.complex.Complex.ComplexMessage.getDefaultInstance()) return this;
        if (other.hasOneDummy()) {
          mergeOneDummy(other.getOneDummy());
        }
        if (multipleDummyBuilder_ == null) {
          if (!other.multipleDummy_.isEmpty()) {
            if (multipleDummy_.isEmpty()) {
              multipleDummy_ = other.multipleDummy_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureMultipleDummyIsMutable();
              multipleDummy_.addAll(other.multipleDummy_);
            }
            onChanged();
          }
        } else {
          if (!other.multipleDummy_.isEmpty()) {
            if (multipleDummyBuilder_.isEmpty()) {
              multipleDummyBuilder_.dispose();
              multipleDummyBuilder_ = null;
              multipleDummy_ = other.multipleDummy_;
              bitField0_ = (bitField0_ & ~0x00000001);
              multipleDummyBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getMultipleDummyFieldBuilder() : null;
            } else {
              multipleDummyBuilder_.addAllMessages(other.multipleDummy_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        example.complex.Complex.ComplexMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (example.complex.Complex.ComplexMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private example.complex.Complex.DummyMessage oneDummy_;
      private com.google.protobuf.SingleFieldBuilderV3<
          example.complex.Complex.DummyMessage, example.complex.Complex.DummyMessage.Builder, example.complex.Complex.DummyMessageOrBuilder> oneDummyBuilder_;
      /**
       * <code>.example.complex.DummyMessage one_dummy = 2;</code>
       * @return Whether the oneDummy field is set.
       */
      public boolean hasOneDummy() {
        return oneDummyBuilder_ != null || oneDummy_ != null;
      }
      /**
       * <code>.example.complex.DummyMessage one_dummy = 2;</code>
       * @return The oneDummy.
       */
      public example.complex.Complex.DummyMessage getOneDummy() {
        if (oneDummyBuilder_ == null) {
          return oneDummy_ == null ? example.complex.Complex.DummyMessage.getDefaultInstance() : oneDummy_;
        } else {
          return oneDummyBuilder_.getMessage();
        }
      }
      /**
       * <code>.example.complex.DummyMessage one_dummy = 2;</code>
       */
      public Builder setOneDummy(example.complex.Complex.DummyMessage value) {
        if (oneDummyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          oneDummy_ = value;
          onChanged();
        } else {
          oneDummyBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.example.complex.DummyMessage one_dummy = 2;</code>
       */
      public Builder setOneDummy(
          example.complex.Complex.DummyMessage.Builder builderForValue) {
        if (oneDummyBuilder_ == null) {
          oneDummy_ = builderForValue.build();
          onChanged();
        } else {
          oneDummyBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.example.complex.DummyMessage one_dummy = 2;</code>
       */
      public Builder mergeOneDummy(example.complex.Complex.DummyMessage value) {
        if (oneDummyBuilder_ == null) {
          if (oneDummy_ != null) {
            oneDummy_ =
              example.complex.Complex.DummyMessage.newBuilder(oneDummy_).mergeFrom(value).buildPartial();
          } else {
            oneDummy_ = value;
          }
          onChanged();
        } else {
          oneDummyBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.example.complex.DummyMessage one_dummy = 2;</code>
       */
      public Builder clearOneDummy() {
        if (oneDummyBuilder_ == null) {
          oneDummy_ = null;
          onChanged();
        } else {
          oneDummy_ = null;
          oneDummyBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.example.complex.DummyMessage one_dummy = 2;</code>
       */
      public example.complex.Complex.DummyMessage.Builder getOneDummyBuilder() {
        
        onChanged();
        return getOneDummyFieldBuilder().getBuilder();
      }
      /**
       * <code>.example.complex.DummyMessage one_dummy = 2;</code>
       */
      public example.complex.Complex.DummyMessageOrBuilder getOneDummyOrBuilder() {
        if (oneDummyBuilder_ != null) {
          return oneDummyBuilder_.getMessageOrBuilder();
        } else {
          return oneDummy_ == null ?
              example.complex.Complex.DummyMessage.getDefaultInstance() : oneDummy_;
        }
      }
      /**
       * <code>.example.complex.DummyMessage one_dummy = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          example.complex.Complex.DummyMessage, example.complex.Complex.DummyMessage.Builder, example.complex.Complex.DummyMessageOrBuilder> 
          getOneDummyFieldBuilder() {
        if (oneDummyBuilder_ == null) {
          oneDummyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              example.complex.Complex.DummyMessage, example.complex.Complex.DummyMessage.Builder, example.complex.Complex.DummyMessageOrBuilder>(
                  getOneDummy(),
                  getParentForChildren(),
                  isClean());
          oneDummy_ = null;
        }
        return oneDummyBuilder_;
      }

      private java.util.List<example.complex.Complex.DummyMessage> multipleDummy_ =
        java.util.Collections.emptyList();
      private void ensureMultipleDummyIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          multipleDummy_ = new java.util.ArrayList<example.complex.Complex.DummyMessage>(multipleDummy_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          example.complex.Complex.DummyMessage, example.complex.Complex.DummyMessage.Builder, example.complex.Complex.DummyMessageOrBuilder> multipleDummyBuilder_;

      /**
       * <code>repeated .example.complex.DummyMessage multiple_dummy = 3;</code>
       */
      public java.util.List<example.complex.Complex.DummyMessage> getMultipleDummyList() {
        if (multipleDummyBuilder_ == null) {
          return java.util.Collections.unmodifiableList(multipleDummy_);
        } else {
          return multipleDummyBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .example.complex.DummyMessage multiple_dummy = 3;</code>
       */
      public int getMultipleDummyCount() {
        if (multipleDummyBuilder_ == null) {
          return multipleDummy_.size();
        } else {
          return multipleDummyBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .example.complex.DummyMessage multiple_dummy = 3;</code>
       */
      public example.complex.Complex.DummyMessage getMultipleDummy(int index) {
        if (multipleDummyBuilder_ == null) {
          return multipleDummy_.get(index);
        } else {
          return multipleDummyBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .example.complex.DummyMessage multiple_dummy = 3;</code>
       */
      public Builder setMultipleDummy(
          int index, example.complex.Complex.DummyMessage value) {
        if (multipleDummyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMultipleDummyIsMutable();
          multipleDummy_.set(index, value);
          onChanged();
        } else {
          multipleDummyBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .example.complex.DummyMessage multiple_dummy = 3;</code>
       */
      public Builder setMultipleDummy(
          int index, example.complex.Complex.DummyMessage.Builder builderForValue) {
        if (multipleDummyBuilder_ == null) {
          ensureMultipleDummyIsMutable();
          multipleDummy_.set(index, builderForValue.build());
          onChanged();
        } else {
          multipleDummyBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .example.complex.DummyMessage multiple_dummy = 3;</code>
       */
      public Builder addMultipleDummy(example.complex.Complex.DummyMessage value) {
        if (multipleDummyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMultipleDummyIsMutable();
          multipleDummy_.add(value);
          onChanged();
        } else {
          multipleDummyBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .example.complex.DummyMessage multiple_dummy = 3;</code>
       */
      public Builder addMultipleDummy(
          int index, example.complex.Complex.DummyMessage value) {
        if (multipleDummyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMultipleDummyIsMutable();
          multipleDummy_.add(index, value);
          onChanged();
        } else {
          multipleDummyBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .example.complex.DummyMessage multiple_dummy = 3;</code>
       */
      public Builder addMultipleDummy(
          example.complex.Complex.DummyMessage.Builder builderForValue) {
        if (multipleDummyBuilder_ == null) {
          ensureMultipleDummyIsMutable();
          multipleDummy_.add(builderForValue.build());
          onChanged();
        } else {
          multipleDummyBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .example.complex.DummyMessage multiple_dummy = 3;</code>
       */
      public Builder addMultipleDummy(
          int index, example.complex.Complex.DummyMessage.Builder builderForValue) {
        if (multipleDummyBuilder_ == null) {
          ensureMultipleDummyIsMutable();
          multipleDummy_.add(index, builderForValue.build());
          onChanged();
        } else {
          multipleDummyBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .example.complex.DummyMessage multiple_dummy = 3;</code>
       */
      public Builder addAllMultipleDummy(
          java.lang.Iterable<? extends example.complex.Complex.DummyMessage> values) {
        if (multipleDummyBuilder_ == null) {
          ensureMultipleDummyIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, multipleDummy_);
          onChanged();
        } else {
          multipleDummyBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .example.complex.DummyMessage multiple_dummy = 3;</code>
       */
      public Builder clearMultipleDummy() {
        if (multipleDummyBuilder_ == null) {
          multipleDummy_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          multipleDummyBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .example.complex.DummyMessage multiple_dummy = 3;</code>
       */
      public Builder removeMultipleDummy(int index) {
        if (multipleDummyBuilder_ == null) {
          ensureMultipleDummyIsMutable();
          multipleDummy_.remove(index);
          onChanged();
        } else {
          multipleDummyBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .example.complex.DummyMessage multiple_dummy = 3;</code>
       */
      public example.complex.Complex.DummyMessage.Builder getMultipleDummyBuilder(
          int index) {
        return getMultipleDummyFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .example.complex.DummyMessage multiple_dummy = 3;</code>
       */
      public example.complex.Complex.DummyMessageOrBuilder getMultipleDummyOrBuilder(
          int index) {
        if (multipleDummyBuilder_ == null) {
          return multipleDummy_.get(index);  } else {
          return multipleDummyBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .example.complex.DummyMessage multiple_dummy = 3;</code>
       */
      public java.util.List<? extends example.complex.Complex.DummyMessageOrBuilder> 
           getMultipleDummyOrBuilderList() {
        if (multipleDummyBuilder_ != null) {
          return multipleDummyBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(multipleDummy_);
        }
      }
      /**
       * <code>repeated .example.complex.DummyMessage multiple_dummy = 3;</code>
       */
      public example.complex.Complex.DummyMessage.Builder addMultipleDummyBuilder() {
        return getMultipleDummyFieldBuilder().addBuilder(
            example.complex.Complex.DummyMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .example.complex.DummyMessage multiple_dummy = 3;</code>
       */
      public example.complex.Complex.DummyMessage.Builder addMultipleDummyBuilder(
          int index) {
        return getMultipleDummyFieldBuilder().addBuilder(
            index, example.complex.Complex.DummyMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .example.complex.DummyMessage multiple_dummy = 3;</code>
       */
      public java.util.List<example.complex.Complex.DummyMessage.Builder> 
           getMultipleDummyBuilderList() {
        return getMultipleDummyFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          example.complex.Complex.DummyMessage, example.complex.Complex.DummyMessage.Builder, example.complex.Complex.DummyMessageOrBuilder> 
          getMultipleDummyFieldBuilder() {
        if (multipleDummyBuilder_ == null) {
          multipleDummyBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              example.complex.Complex.DummyMessage, example.complex.Complex.DummyMessage.Builder, example.complex.Complex.DummyMessageOrBuilder>(
                  multipleDummy_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          multipleDummy_ = null;
        }
        return multipleDummyBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:example.complex.ComplexMessage)
    }

    // @@protoc_insertion_point(class_scope:example.complex.ComplexMessage)
    private static final example.complex.Complex.ComplexMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new example.complex.Complex.ComplexMessage();
    }

    public static example.complex.Complex.ComplexMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ComplexMessage>
        PARSER = new com.google.protobuf.AbstractParser<ComplexMessage>() {
      @java.lang.Override
      public ComplexMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ComplexMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ComplexMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ComplexMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public example.complex.Complex.ComplexMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DummyMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:example.complex.DummyMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * Protobuf type {@code example.complex.DummyMessage}
   */
  public  static final class DummyMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:example.complex.DummyMessage)
      DummyMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DummyMessage.newBuilder() to construct.
    private DummyMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DummyMessage() {
      name_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new DummyMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DummyMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return example.complex.Complex.internal_static_example_complex_DummyMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return example.complex.Complex.internal_static_example_complex_DummyMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              example.complex.Complex.DummyMessage.class, example.complex.Complex.DummyMessage.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof example.complex.Complex.DummyMessage)) {
        return super.equals(obj);
      }
      example.complex.Complex.DummyMessage other = (example.complex.Complex.DummyMessage) obj;

      if (getId()
          != other.getId()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static example.complex.Complex.DummyMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static example.complex.Complex.DummyMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static example.complex.Complex.DummyMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static example.complex.Complex.DummyMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static example.complex.Complex.DummyMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static example.complex.Complex.DummyMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static example.complex.Complex.DummyMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static example.complex.Complex.DummyMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static example.complex.Complex.DummyMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static example.complex.Complex.DummyMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static example.complex.Complex.DummyMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static example.complex.Complex.DummyMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(example.complex.Complex.DummyMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code example.complex.DummyMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:example.complex.DummyMessage)
        example.complex.Complex.DummyMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return example.complex.Complex.internal_static_example_complex_DummyMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return example.complex.Complex.internal_static_example_complex_DummyMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                example.complex.Complex.DummyMessage.class, example.complex.Complex.DummyMessage.Builder.class);
      }

      // Construct using example.complex.Complex.DummyMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        name_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return example.complex.Complex.internal_static_example_complex_DummyMessage_descriptor;
      }

      @java.lang.Override
      public example.complex.Complex.DummyMessage getDefaultInstanceForType() {
        return example.complex.Complex.DummyMessage.getDefaultInstance();
      }

      @java.lang.Override
      public example.complex.Complex.DummyMessage build() {
        example.complex.Complex.DummyMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public example.complex.Complex.DummyMessage buildPartial() {
        example.complex.Complex.DummyMessage result = new example.complex.Complex.DummyMessage(this);
        result.id_ = id_;
        result.name_ = name_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof example.complex.Complex.DummyMessage) {
          return mergeFrom((example.complex.Complex.DummyMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(example.complex.Complex.DummyMessage other) {
        if (other == example.complex.Complex.DummyMessage.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        example.complex.Complex.DummyMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (example.complex.Complex.DummyMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:example.complex.DummyMessage)
    }

    // @@protoc_insertion_point(class_scope:example.complex.DummyMessage)
    private static final example.complex.Complex.DummyMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new example.complex.Complex.DummyMessage();
    }

    public static example.complex.Complex.DummyMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DummyMessage>
        PARSER = new com.google.protobuf.AbstractParser<DummyMessage>() {
      @java.lang.Override
      public DummyMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DummyMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DummyMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DummyMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public example.complex.Complex.DummyMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_example_complex_ComplexMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_example_complex_ComplexMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_example_complex_DummyMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_example_complex_DummyMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rcomplex.proto\022\017example.complex\"y\n\016Comp" +
      "lexMessage\0220\n\tone_dummy\030\002 \001(\0132\035.example." +
      "complex.DummyMessage\0225\n\016multiple_dummy\030\003" +
      " \003(\0132\035.example.complex.DummyMessage\"(\n\014D" +
      "ummyMessage\022\n\n\002id\030\001 \001(\005\022\014\n\004name\030\002 \001(\tb\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_example_complex_ComplexMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_example_complex_ComplexMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_example_complex_ComplexMessage_descriptor,
        new java.lang.String[] { "OneDummy", "MultipleDummy", });
    internal_static_example_complex_DummyMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_example_complex_DummyMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_example_complex_DummyMessage_descriptor,
        new java.lang.String[] { "Id", "Name", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
